### ISSUE TITLE
GNOME greeter shows the Ubuntu logo and text after installation

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Development/celos#13]
After installation the GNOME greeter shows the Ubuntu logo and buttons that say "start using Ubuntu"

Is there a way this can be edited and where?

Many thanks,
Adam Salt

**Comment by locness3** [comment]
You mean the gnome-welcome-tour? I'd say this is hardcoded but I could be wrong.

**Comment by whyadamsalt** [comment]
Yeah that's what I mean, thank you!

**Comment by whyadamsalt** [comment]
Easy fix, Change the "Ubuntu" in /etc/os-release (first line) to "CelOS"
This will be done tomorrow.

**Comment by whyadamsalt** [comment]
> Easy fix, Change the "Ubuntu" in /etc/os-release (first line) to "CelOS"
> This will be done tomorrow.

This wasn't the fix. However I have found a command which will disable GNOME greeter entirely, which may work!
`sudo bash -c 'echo "X-GNOME-Autostart-enabled=false" >> /etc/xdg/autostart/gnome-initial-setup-first-login.desktop'`

**Comment by locness3** [comment]
wow

**Comment by whyadamsalt** [comment]
> wow

What?

**Comment by whyadamsalt** [comment]
Alternatively in /etc/skel i can make a .config file and place gnome-initial-setup-done inside of it, which is the option I will likely use.e

**Comment by whyadamsalt** [comment]
Fixed
