### ISSUE TITLE
URGENT ISSUE - Grub is broken on UEFI systems. System is unable to boot and is placed into Grub Rescue.

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Development/celos#18]
The grub install fails for UEFI systems and only seems to work for BIOS. When booting it places in grub rescue.

**Comment by locness3** [comment]
Needs additionnal troubleshooting from someone who knows what they're doing.

**Comment by whyadamsalt** [comment]
> Needs additionnal troubleshooting from someone who knows what they're doing.

From what I gather the grub will install on systems with BIOS, but runs into an issue with UEFI. My first guess is an issue in grub.cfg, or a missing UEFI boot partition for grub. I have modified the grub.cfg file. We should find out soon enough and have a fix though!

**Comment by whyadamsalt** [comment]
@locness3 Would enabling systemd-boot fix this issue?

**Comment by locness3** [comment]
They are two different bootloaders, and I guess ubiquity only supports grub - not sure, though.

@whyadamsalt It would be nice if you could go through more troubleshooting, using a live media where needed :

- How's the destination drive partitioned after install (assuming you use the "use full disk" option when installing)?
- What do the /boot and "EFI system partition" contain (show a `tree` and contents of text files) ?
- What are the contents of the generated grub config?
- If you press Esc while booting, to get to grub's options menu, what options are shown?

These results should be compared with those from a regular ubuntu install.

But I think someone else should investigate this issue on different hardware - or are UEFI VMs a thing?

**Comment by whyadamsalt** [comment]
@locness3 UEFI VMs are a thing however I've never successfully created one and seriously dedicated the time to getting one working. For now I will explore alternatives until someone troubleshoots appropriately. 

My few ideas for the issue and potential fixes are:
[grub-efi-amd64-signed did not install](https://answers.launchpad.net/cubic/+question/680446) since I did not have any WiFi drivers present, however this should not occur as I have done a full Ubuntu install without any wireless drivers present. 

[Some grub packages are broken](https://answers.launchpad.net/cubic/+question/692403) and so a simple reinstall will fix this

Another issue could be that /boot/grub.cfg is broken as we have modified that to display "CelOS" rather than "Ubuntu", however I fail to see why this is an issue. 

A potential fix could also be to [enable systemd-boot](https://wiki.archlinux.org/title/Systemd-boot) so that we do not have to deal with the issue of Grub not working on UEFI systems all-together. This should be a last resort as it is preferred that I find out the reason why the system is unable to install grub.

**Comment by locness3** [comment]
:+1: That should have been the initial issue text.

> A potential fix could also be to enable systemd-boot

Yes, but.. you can't just "enable" it like that and get rid of grub. You need the installer - ubiquity - to be aware of it and configure it.

**Comment by whyadamsalt** [comment]
@locness3 Ah right, well that's a bit of a shame. So fixing grub should be the most likely outcome

**Comment by whyadamsalt** [comment]
Issue is now fixed, Broken grub.cfg caused the distro to break on UEFI systems.

**Comment by whyadamsalt** [comment]
I will close this issue when CelOS 1 [Beta v2.0 is released]

**Comment by locness3** [comment]
> I will close this issue when CelOS 1 [Beta v2.0 is released]

If it's been committed to the "source code", it can be closed imo.
