### ISSUE TITLE
[v1.4.1] Change the GDM Screen colour

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Development/celos#6]
Change the GDM Screen colour from purple to grey.
Should be found in /usr/share/gnome-shell/theme/Yaru/ 
- The file for the .gresource has already been created

Have this done by [v1.4.1 Beta]

**Comment by whyadamsalt** [comment]
There are still issues with changing the colour in GDM, so I will likely work on this in a later version.
Chances are I might have to reinstall GDM3.

**Comment by locness3** [comment]
```
sudo update-alternatives --config gdm3-theme.gresource
```
then pick the one that's not Yaru - the Ubuntu logo gets removed too.

@whyadamsalt

**Comment by whyadamsalt** [comment]
@locness3 how do you pick the one that isn't Atari

**Comment by locness3** [comment]
You get a list of items with numbers, one has yaru in it, the other doesn't; you type the number of the one that doesnt

**Comment by locness3** [comment]
then you can safely purge yaru-theme everything

**Comment by whyadamsalt** [comment]
Oh alright, thank you!

**Comment by whyadamsalt** [comment]
When I have time this should be worked on. I am currently in the middle of examinations.

**Comment by whyadamsalt** [comment]
This has now been fixed and will be released in an upcoming ISO!
