### ISSUE TITLE
Change the GNOME/Ubuntu settings panel to match CelOS

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Development/celos#7]
Change GNOME/Ubuntu settings (should be gnome-control-center) to match the needs of CelOS (aka remove Yaru theme changer and Ubuntu logos, etc.)

Would someone be able to tell me where the files for this are located. I have checked out /usr/share/gnome-control-center/ and it doesn't seem to be the correct directory.

Many thanks, Adam.

**Comment by locness3** [comment]
> aka remove Yaru theme changer and Ubuntu logos, etc.

The first problem is resolved by using the stock gnome-session rather than ubuntu-session.

**Comment by whyadamsalt** [comment]
Well how could I default to GNOME-Session and remove Ubuntu-session?

**Comment by locness3** [comment]
```
sudo apt install gnome-session
sudo apt purge ubuntu-session
```

**Comment by whyadamsalt** [comment]
I'll work on that later. I'll see if it's able to just recompile gnome-control-center first, thank you!

**Comment by whyadamsalt** [comment]
Recompiling gnome-control-center doesn't work, I'm testing purging ubuntu-session now

**Comment by whyadamsalt** [comment]
It works as intended and also fixed another issue. Thank you for helping me @locness3 !
