### ISSUE TITLE
Grub still says "Ubuntu"

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Development/celos#9]
Grub says "Ubuntu" rather than "CelOS 1" despite changing the grub.cfg.

**Comment by locness3** [comment]
Did you run update-grub tho

**Comment by whyadamsalt** [comment]
Yes I have ran Update-grub however I'll try do it again when building the next patch.

**Comment by whyadamsalt** [comment]
As far as I am aware this can be closed upon the release of v1.8 as issue #13 solves this issue.

**Comment by whyadamsalt** [comment]
/boot/grub/grub.cfg needs to be changed (this should have already been done though, however some shards may remain in /etc/grub.d/)

**Comment by whyadamsalt** [comment]
Closing as I will be recreating this issue with more detail specific to CelOS 1 [Beta v2.0]
